export enum Country {
  SPAIN = "spain",
  FRANCE = "france",
  ITALY = "italy",
  GERMANY = "germany",
  UK = "uk",
}

export enum Community {
  ANDALUCIA = "andalucia",
  ASTURIAS = "asturias",
  ARAGON = "aragon",
  BALEARIC_ISLANDS = "balearic_islands",
  BASQUE_COUNTRY = "basque_country",
  CANARY_ISLANDS = "canary_islands",
  CANTABRIA = "cantabria",
  CASTILLA_LA_MANCHA = "castilla_la_mancha",
  CASTILLA_LEON = "castilla_leon",
  CATALUNYA = "catalunya",
  CEUTA = "ceuta",
  EXTREMADURA = "extremadura",
  GALICIA = "galicia",
  LA_RIOJA = "la_rioja",
  MADRID = "madrid",
  MELILLA = "melilla",
  MURCIA = "murcia",
  NAVARRA = "navarra",
  VALENCIA = "valencia",
}

export enum Province {
  ALMERIA = "almeria",
  CADIZ = "cadiz",
  CORDOBA = "cordoba",
  GRANADA = "granada",
  HUELVA = "huelva",
  JAEN = "jaen",
  MALAGA = "malaga",
  SEVILLA = "sevilla",
  HUESCA = "huesca",
  TERUEL = "teruel",
  ZARAGOZA = "zaragoza",
  ASTURIAS = "asturias",
  BALEARIC_ISLANDS = "balearic_islands",
  ALAVA = "alava",
  GUIPUZCOA = "guipuzcoa",
  VIZCAYA = "vizcaya",
  LAS_PALMAS = "las_palmas",
  SANTA_CRUZ_DE_TENERIFE = "santa_cruz_de_tenerife",
  CANTABRIA = "cantabria",
  ALBACETE = "albacete",
  CIUDAD_REAL = "ciudad_real",
  CUENCA = "cuenca",
  GUADALAJARA = "guadalajara",
  TOLEDO = "toledo",
  AVILA = "avila",
  BURGOS = "burgos",
  LEON = "leon",
  PALENCIA = "palencia",
  SALAMANCA = "salamanca",
  SEGOVIA = "segovia",
  SORIA = "soria",
  VALLADOLID = "valladolid",
  ZAMORA = "zamora",
  BARCELONA = "barcelona",
  GERONA = "gerona",
  LERIDA = "lerida",
  TARRAGONA = "tarragona",
  CEUTA = "ceuta",
  BADAJOZ = "badajoz",
  CACERES = "caceres",
  A_CORUNA = "a_coruna",
  LUGO = "lugo",
  ORENSE = "orense",
  PONTEVEDRA = "pontevedra",
  LA_RIOJA = "la_rioja",
  MADRID = "madrid",
  MELILLA = "melilla",
  MURCIA = "murcia",
  NAVARRA = "navarra",
  VALENCIA = "valencia",
}
